# Generated by Django 3.2.25 on 2024-04-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20240421_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
